services:
  - type: web
    name: call-quality-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SYSTEM_URL
        value: https://call-quality-system.onrender.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
